# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  # Pods for VK

end
